### ISSUE TITLE
Erro de validação ao enviar um array de hashes como form-urlencoded

### ISSUE THREAD

**Issue by ppadron** [vindi/vindi-php#1]
Olá!

Antes de abrir um PR preferi postar meu commit aqui p/ discussão.

Por padrão, as requisições à API da Vindi são serializadas no formato x-www-form-urlencoded, mas isso gera um erro de validação ao enviar um array de hashes. Esbarrei nesse erro ao criar uma nova assinatura usando o SDK, onde precisei informar o atributo _product_items_, que é um array de hashes.

Para evitar problemas de serialização, passei a usar JSON em vez de Form:

https://github.com/templateria/vindi-php/commit/2b0796b22d941e2b7bbb29dcd266d43f68bbda4c

Já passei por isso aqui na Templateria: nosso backend é Grape e o frontend é Lithium (PHP). Sempre que eu definia um endpoint que aceitava um paramêtro com `type: Array[OutraClasse]` encontrava problemas. Creio que isso acontece porque a função `http_build_query` do PHP adiciona índices nos arrays. Depois dessa dor de cabeça, passei a usar JSON apenas.

Acham que é uma boa mudar aqui também?

**Comment by talesgalvao** [comment]
Olá, Pedro

Estou entrando agora no time de desenvolvimento da Vindi, muito obrigado pela sugestão, assim que possível vamos olhar essa issue e atualizo por aqui sobre qualquer novidade.

Obrigado

**Comment by talesgalvao** [comment]
Olá @ppadron,

Novamente obrigado pelo toque, já ajustamos o método de envio para JSON. 

Att
