### ISSUE TITLE
Não é possível passar parâmetros para ações de delete

### ISSUE THREAD

**Issue by brunocalza** [vindi/vindi-php#11]
Estou tentando deletar uma subscription, pela documentação é possível passar o parâmetro cancel_bills. Mas a função delete não permite passar nenhum parâmetro

```
 public function delete($id = null) {
        return $this->apiRequester->request('DELETE', $this->url($id));
 }
```

**Comment by talesgalvao** [comment]
Olá Bruno,
estamos analisando e em breve faremos as atualizações necessárias.

Att Tales Galvão
