### ISSUE TITLE
Versão aprimorada do Try Catch para o php Exception.

### ISSUE THREAD

**Issue by rodrigoguerrasa** [vindi/vindi-php#12]
O try catch block clássico:

```
        try {
            $customer_subscription = $this->customer_subscription_service->all($query);
        }

        catch (Exception $except) {
            $status = array('Subs Ld', $except->getMessage(), 'critico');         
        }
```

quando dá errado, faz com que o getMessage() apresente o erro:

> "Erros de validação foram encontrados!"

Mas este tipo de erro é muito amplo.  O desenvolvedor fica sem saber se o erro é na duplicação do "code", se o erro é na sigla do Estado quando um cliente novo está sendo inserido, se o erro é no telefone, etc.

Para conseguir uma visão mais específica do erro com o mesmo try catch block, considere adicionar as seguintes linhas de código no arquivo ValidationException.php, dentro do __construct:

```
public function __construct($status, $errors, array $lastOptions = [])
    {
        parent::__construct($status, $errors, $lastOptions);
        // novo código inserido -- start
        $error_log = '';
        if ( is_array( $errors ) ) {
            if ( !empty($errors) ) {
                $error_log .= ' --- ' . $errors[0]->id . ' --- ' . $errors[0]->parameter . ' --- ' . $errors[0]->message . ' --- ' ;
            }
        }
        // novo código inserido -- end

        $this->message     = "Erros de validação foram encontrados!" . $error_log;  // $error_log appended to error message.
    }
```

Dessa forma fica fácil saber o erro específico, um de cada vez, com PHP puro, sem precisar instalar, instanciar um novo objeto do Guzzle dentro de um namespace específico.

Boa sorte!

**Comment by odirleiborgert** [comment]
Concordo com o @rodrigoguerrasa que dessa forma fica algo muito genérico. 

Outra dúvida, essa biblioteca está abandonada?

**Comment by bissolli** [comment]
Acabei de criar a PR #18 com essa melhoria! Vamos ver se aceitam.

**Comment by rodrigoguerrasa** [comment]
Boa!

**Comment by odirleiborgert** [comment]
Show!

**Comment by lyoncesar** [comment]
Boa tarde pessoal, tudo bem?
Primeiro quero pedir desculpas pela demora em responder essa issue.
O @bissolli fez o PR ele foi rejeitado porque optamos por criar uma nova versão da SDK corrigindo algumas limitações dela, como o tratamento de erros, response, uso da chave api e o servidor de destino. Vamos usar a ideia do @bissolli para o tratamento de erros e assim que a nova versão estiver disponível nós avisamos aqui no projeto mesmo.
Por enquanto eu estou encerrando essa issue.

Abs.

**Comment by denispsilva** [comment]
Boa noite @rodrigoguerrasa, realizei a alteração no código como indicado.
Mas o resultado continua sendo o mesmo, consegue me ajudar por favor?
