### ISSUE TITLE
Respostas retornam apenas o primeiro elemento do array

### ISSUE THREAD

**Issue by andersondalmina** [vindi/vindi-php#19]
Como a resposta retornam sempre o primeiro elemento do array, algumas requisições que deveriam retornam mais informações acabam retornando apenas uma parte delas.

**Exemplo:** ao criar uma assinatura deveria receber o objeto da assinatura criada juntamente com as cobranças e transações, mas está retornando apenas a assinatura.

**Comment by vinicrf** [comment]
Exatamente. E eu me matando pensando que tinha algo errado. Dei uma olhada no método response da class ApiRequester e estava lá o problema. Sempre é apontado para o primeiro elemento da resposta. Fiz uma pequena alteração e resolvido o problema.  

`$this->lastResponse = $response;

        $content = $response->getBody()->getContents();

        $decoded = json_decode($content); // parse as object
        $data = $decoded;
        $count = count((array)$decoded);
        if ($count == 1){
            reset($decoded);
            $data = current($decoded); // get first attribute from array, e.g.: subscription, subscriptions, errors.
        }

        $this->checkRateLimit($response)
            ->checkForErrors($response, $data);

        return $data;`

**Comment by andersondalmina** [comment]
@vinicrf Legal, abre um PR para subirmos essa correção no master 👍

**Comment by lyoncesar** [comment]
@andersondalmina, tudo bem?
Estou encerrando essa issue, vou fazer um PR amanhã com essa sugestão do @vinicrf.
Obrigado pela ajuda pessoal.

Abs.

**Comment by ghost** [comment]
Entrei em contato com o suporte da Vindi hoje (26/07/2018) sobre esse assunto e a recomendação foi:

> Não caracteriza erro. É necessário utilizar um método a mais:
> ![inline-654106058](https://user-images.githubusercontent.com/14889949/43219787-a86de48a-901e-11e8-8122-a12e8556d4ea.png)
> 

Creio que é uma solução muito boa e eficaz. 

=> Pois assim, mantêm o padrão da SDK, que toda ação contra uma entidade (Bill / Subscription / Product etc) retorna a própria entidade atualizada, não precisando tratar individualmente casos pontuais como Subscription que retorna 2 entidades.

Creio que pelos motivos expostos acima, eles não fizeram nenhuma alteração no código-fonte conforme sugerido acima.
