### ISSUE TITLE
Parâmetro Modo Sandbox

### ISSUE THREAD

**Issue by ghost** [vindi/vindi-php#22]
Acredito que falta um parâmetro indicando que desejamos usar o modo Sandbox.

Quando estamos usando ambiente "real" (produção) ou "sandbox trial", a URL da API é
```php
public static $apiBase = 'https://app.vindi.com.br/api/v1/';
```

Porém, em ambiente de sandbox (sem trial), a URL correta é:
```php
public static $apiBase = 'https://sandbox-app.vindi.com.br/api/v1/';
```
Poderíamos passar como variável de ambiente, a exemplo da "VINDI_API_KEY", ex:
```php
putenv('VINDI_API_KEY=A1B2C3D4E5');
putenv('VINDI_SANDBOX=1');
```

Local:
https://github.com/vindi/vindi-php/blob/a5f13db8cd9359c4e611e55f2f2b754e45a478ff/src/Vindi.php#L17

```src/Vindi.php

**Comment by vinicrf** [comment]
Percebi essa necessidade também. Você pode acessar o atributo estático $apiBase e modificar a url.
`\Vindi\Vindi::$apiBase = 'https://sandbox-app.vindi.com.br/api/v1/';

**Comment by ghost** [comment]
@vinicrf boa, obrigado pela dica! algum moderador da Vindi poderia dar uma olhada e responder para a gente né. Vamos ver, senão, vou encaminhar no suporte técnico deles.

**Comment by vitor-adonai** [comment]
@vitorccsiqueira Acho a equipe da Vindi faz vista grossa quanto as integrações.
 API deles é terrível em todos os sentidos.
 Pleno 2017 e até hoje a validação não passa de um "Erros de validação foram encontrados!".

 Lamentável!

**Comment by vinicrf** [comment]
Concordo com você. As sdk estão abandonadas. Isso é fato. Da a entender que a equipe de Ti é terceirizada. Nesse caso da sandbox foi um grande exemplo. Lançar um serviço de sandbox sem atualizar as sdk é um grande erro. O correto é sair de variáveis de ambiente e criar uma class Config e um arquivo de config também e fazer as verificações na inicialização da class Vindi. Mas parece que nossas opiniões não são levadas em conta(ou talvez não tenha ninguém por aqui as vendo).

**Comment by lyoncesar** [comment]
Boa tarde @vitorccsiqueira e @vinicrf. Tudo bem?
Obrigado pelos comentários.
A sugestão do endereço para a api sandbox vai funcionar.
Nós estamos trabalhando numa nova versão da sdk, onde serão removidas as variáveis de ambiente, também será possível indicar qual api será usada na requisição e inclui melhorias no response e tratamento de erros.

@vinicrf, as sugestões feitas no seu último comentário fazem sentido para a biblioteca, inclusive o projeto é opensource e você pode fazer PRs também. Se fizerem sentido para a biblioteca eles serão aceitos sem dificuldades. :-)

Caso tenham alguma dúvida sobre a biblioteca ou nossa api o canal indicado para isso é o suporte técnico mesmo, em atendimento.vind.com.br ou no e-mail (atendimento@vindi.com.br).

Mais uma vez agradecemos a participação de vocês e também contamos com mais sugestões e PRs :-)

Abs.

**Comment by vitor-adonai** [comment]
@lyoncesar O principal até hoje não existe.
 Retornar o erro na validação da API.
 👎

**Comment by lyoncesar** [comment]
Oi @vitor-adonai 
Realmente ainda não temos o retorno ideal na validação da API :(
Mas estamos trabalhando em uma nova versão da SDK que vai incluir isso, por enquanto uma opção é o uso do try catch mesmo, como no exemplo abaixo:
![screenshot from 2017-10-17 11-53-07](https://user-images.githubusercontent.com/15332442/31668751-d1b41d16-b331-11e7-91f2-92907116c29c.png)

Se você tiver sugestões de boas práticas para fazermos isso elas serão bem vindas, pode abrir uma issue ou um PR aqui no Github mesmo, ou enviar no e-mail: integracoes@vindi.com.br :)

Abs.
