### ISSUE TITLE
Parse da chave "bill" ignorada ao fazer um request em "subscription"

### ISSUE THREAD

**Issue by batistahermogenes** [vindi/vindi-php#25]
Devido a uma necessidade, acabei detectando um problema com a Lib, na hora de fazer uma subscription e verificar se o pagamento foi efetuado com sucesso, o json original retornado devolve `subscription` e `bill`, porém, ao fazer o parse e devolver o objeto do response nesta Lib, vocês estão associando apenas o que foi retornado no `subscription`, ignorando totalmente o que foi retornado em `bill`, fiz um workaround local pra resolver isso, que foi fazer o parse do response original e pegar as informações que necessitava, como segue o código abaixo (PS: no exemplo abaixo, `customer_id` e `plan_id` são dados falsos):
```php
$data = array(
    "plan_id" => 12356, 
    "customer_id" => 12356,
    "payment_method_code" => "credit_card",
);
$subscriptionManage = new Vindi\Subscription;
$subscription = $subscriptionManage->create($data);
$body = json_decode((string) $subscriptionManage->getLastResponse()->getBody());
if($body->bill->status != 'paid') {
   // Lógica para cancelar a inscrição aqui
}
```
Talvez adicionando os dados de `bill` dentro da classe retornada, com um atributo de mesmo nome (`bill`), resolveria o problema, isso evitaria ter que fazer toda essa volta que fiz, pra conseguir a informação que precisava, podendo fazer um acesso direto, como:
```php
echo $subscription->bill->status;
```

**Comment by lyoncesar** [comment]
Boa tarde @batistahermogenes, tudo bem?
Obrigado pelo sugestão.
Nós estamos trabalhando em uma nova versão da SDK, onde o response será revisado.
Por enquanto você consegue resolver isso usando o 'get_last_response':
![screenshot from 2017-10-16 14-58-52](https://user-images.githubusercontent.com/15332442/31624834-c034fe70-b282-11e7-94ae-bb216e01421f.png)
Me avise se não conseguir com ele.

Abs.

**Comment by batistahermogenes** [comment]
Como falei na abertura da issue, eu resolvi justamente pegando o `getLastResponse()`.

**Comment by lyoncesar** [comment]
Legal @batistahermogenes.
Nós estamos trabalhando em uma nova versão da SDK e essa parte do response será revisada.
Mais uma vez, obrigado pela sugestão.

Abs.
