### ISSUE TITLE
Assinatura não retorna objeto fatura 

### ISSUE THREAD

**Issue by vitorini** [vindi/vindi-php#35]
Olá, fiz um teste de assinatura na pagina sandbox de vcs e percebi um retorno completo, quando fiz download da sua SDK, além de ter que instalar várias bibliotecas que não estão no projeto, ele não retornou a futura (objeto BILL) sendo que usei o mesmo json de request da sua pagina sandbox. Vocês tem algum exemplo melhor do que aprensentado nessa biblioteca?  Ou alguma ideia do pq isso ocorre?

**Comment by rtakauti** [comment]
Ola @vitorini, desculpe a demora para responder.

No nosso README.md colocamos um código que pode te ajudar a visualizar o objeto Bill

- Segue o trecho do README com o código:

Response: Caso precise de mais detalhes sobre a resposta de cada request, utilize o método getLastResponse. Se nenhum request foi efetuado anteriormente, este método retornará NULL.

// Retorna os dados da última resposta recebida dos servidores da Vindi
$lastResponse = $customerService->getLastResponse();

// Retorna o corpo da requisição
$body = (string) $customerService->getLastResponse()->getBody();
// Retorna o HTTP Status Code
$lastResponse->getStatusCode();
// Retorna o todos os headers
$lastResponse->getHeaders();
// Retorna um único header
$lastResponse->getHeader('Header-Name');
