### ISSUE TITLE
melhorar forma de usar chave de api

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [vindi/vindi-php#36]
Seria bom se tivesse outra maneira de usar a chave além de putenv. Por exemplo enviar junto a requisição, dessa forma seria possível usar clients http para fazer testes por exemplo.

**Comment by rtakauti** [comment]
Ola @diego-lipinski-de-castro, muito obrigado pela sugestão.
E sim já, estamos vendo uma outra maneira de não só utilizar as variáveis de ambiente como forma de entrada da chave API.
