### ISSUE TITLE
 Erro na validação ao atualizar um Customers 

### ISSUE THREAD

**Issue by vitor-adonai** [vindi/vindi-php#45]
Olá, na hora que eu vou atualizar um customer, o state sempre dá erro na validação.
 Na documentação diz: state (string, opcional): Código do estado no formato ISO 3166-2. Exemplo: SP. Porém, ao atualizar com SP (string), retorna erro na validação.
 Após horas quebrando a cabeça, eu percebi que state não é obrigatório para gerar boletos (contrariando o que o suporte havia dito).

 Não seria um problema não aceitar SP como State? A própria documentação cita SP como exemplo.
 https://vindi.github.io/api-docs/dist/#!/customers/PUT_version_customers_id_format

 Obrigado!

**Comment by carolina-y** [comment]
@vitor-adonai olá, tudo bem? O Customer já tem o `country` no `address` setado como BR?

**Comment by vitor-adonai** [comment]
Olá @carolina-y, eu testei com e sem country.
 Como eu já consegui resolver o problema deixando sem state, eu já publiquei as alterações em produção.
 O resultado final ficou:
`
$customer = $customerService->update(Auth::user()->vindiid,
            [
                'registry_code' => $request->cpf,
                'address' => [
                    'street' => $request->rua,
                    'number' => $request->numero,
                    'neighborhood' => $request->bairro,
                    'city' => $request->cidade,
                    //'state' => 'SP',
                    'zipcode' => $request->cep
                ]

            ]
        );
`
 Obrigado!

**Comment by carolina-y** [comment]
Sem problemas. Se precisar do state de qualquer forma, acredito que o country e o state funcionam, pois o state depende do country em que o customer é inserido. Obrigada pelo feedback!
