### ISSUE TITLE
Erro de sintaxe

### ISSUE THREAD

**Issue by fernando-rr** [vindi/vindi-php#48]
**Descreva o bug**
Tentando usar string como objeto. Possível mudança de retorno da API.

**Como reproduzir**
Passos para reprodução do comportamento:
1. Instanciar o serviço \Vindi\Merchant sem o parâmetro "role";
2. Usar o método create;

**Comportamento Esperado**
Tratamento de exceptions

**Prints de tela**
Retorno recebido na exception
![captura de tela 2018-07-17 as 11 00 42](https://user-images.githubusercontent.com/2156601/42822177-be6ee12c-89b0-11e8-9e85-177fed2ddb4d.png)
:sweat_smile:

**Comment by fernando-rr** [comment]
PS: o erro foi gerado por eu estar tentando fazer um post no Merchant achando que era o Merchant User.

**Comment by rtakauti** [comment]
Tudo bem @fernando-rr ,

Eu entendo que foi uma surpresa tentar acessar o `create` do Merchant que não existe no lado da API da Vindi, concordo que o melhor a fazer era sim disparar uma `Exception`, mas é algo super valorizado a sua observação para falar a verdade qualquer forma de contribuição é muito bem vinda.

**Comment by rtakauti** [comment]
Qualquer dúvida ou sugestão favor entrar em contato com a gente !!! :smile: :+1:
