### ISSUE TITLE
A classe Movement não foi publicada no https://packagist.org

### ISSUE THREAD

**Issue by HelioDantas** [vindi/vindi-php#54]
**Descreva o bug**
A classe  Movement.php subiu para master, porem não foi criada uma nova release e também não foi publicada no packagist.
Com isso não é possível usar o gerenciador de dependências da maneira correta.

**Contexto adicional**

**Comment by st3llaris** [comment]
Bom dia Helio, tudo bem?

Muito obrigado pelas informações! Já publicamos a release e também publicamos no Packagist. Você pode verificar a release [nesse link](https://github.com/vindi/vindi-php/releases/tag/1.2.2).
