### ISSUE TITLE
Parâmetros método busca all

### ISSUE THREAD

**Issue by oniram** [vindi/vindi-php#62]
Como passar o tipo de consulta para realizar filtros com o método all (Resource.php) ?
Exemplo: Eu gostaria de filtrar Bill onde created_at seja >= alguma data

**Comment by rbarros** [comment]
Para fazer as buscas deve adicionar o parâmetro query e seguir a regra da documentação da [Vindi](https://atendimento.vindi.com.br/hc/pt-br/articles/204163150).

```php
$bills = $billService->all([
    'query' => 'created_at>="2021-01-28"',
    'sort_by'    => 'created_at',
    'sort_order' => 'desc'
]);
```
O Guzzle monta a url desta forma:
```
string(63) "query=created_at%3E%3D%222021-01-28%22&sort_by=created_at&sort_order=desc"
```
