### ISSUE TITLE
Update para Guzzle 7

### ISSUE THREAD

**Issue by robertotcestari** [vindi/vindi-php#65]
**Sua requisição de nova feature é relacionado ao problema?. Por favor descreva-o**
As versões mais novas do Laravel possuem dependência do Guzzle na versão 7. Esse pacote aceita apenas o Guzzle v. 6

**Descreva a solução que você gostaria que a gente implementasse**
Update para Guzzle 7

**Comment by tmazza** [comment]
@robertotcestari Subi o PR https://github.com/vindi/vindi-php/pull/68 como rascunho, fazendo o upgrade dos pacotes e atualizando os testes unitários.

Todos os testes unitário estão passando, porém acho válido mais alguns testes de integração. Nos próximos dias devo conectar esse PR com a nossa aplicação e fazer mais requisições usando o Sandbox, para garantir que esta tudo ok mesmo.

Pode ser de teu interesse já dar uma olhada e ver se nada quebra no contexto da aplicação de vocês.

**Comment by marcallkz** [comment]
alguma previsão para o release da atualização?

**Comment by laerte-guimaraes** [comment]
@marcallkz a versão (1.3.0) agora já está disponível via [composer](https://packagist.org/packages/vindi/vindi-php) 😉
